---
title: "Javascript"
author: "Jan-Philipp Kolb"
date: "27. Juli 2015"
output: ioslides_presentation
---

## Javascript

- [Fiddles](http://jsfiddle.net/user/opencpu/fiddles/)

- Jeroen Ooms - [Introducing V8: An Embedded JavaScript Engine for R](https://www.opencpu.org/posts/v8-release-0-2/)
<https://www.r-bloggers.com/introducing-v8-an-embedded-javascript-engine-for-r/>

## R and Javascript

- [Statistical computation in JavaScript — am I nuts?](http://www.r-bloggers.com/statistical-computation-in-javascript-am-i-nuts/)

- [Bring the best of JavaScript data visualization to R](http://www.htmlwidgets.org/)

- [an-example-of-writing-native-javascript-bindings-in-r](http://www.r-bloggers.com/minimist-an-example-of-writing-native-javascript-bindings-in-r/)


- [d3-cartographic-envy-with-r-ggplot](http://rud.is/b/2014/09/26/overcoming-d3-cartographic-envy-with-r-ggplot/)

- [Javascript and d3 for R users](http://civilstat.com/2012/10/basics-of-javascript-and-d3-for-r-users/)

```{r,eval=F}
library(r2d3)
```



## Running javascript using V8


```{r,eval=F}
library(V8)
data(diamonds, package="ggplot2")
ct <- new_context()
ct$assign("diamonds", diamonds)
 
# Load CrossFilter JavaScript library
ct$source("http://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.min.js")
ct$console()
```

- [File ending .js](http://www.dateiendung.com/format/js)



