---
title: "Neural Networks"
author: "Jan-Philipp Kolb"
date: "1 September 2016"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F,message = F)
```

## [Choice Modeling vs. Neural Networks ](http://joelcadwell.blogspot.de/2016/03/understanding-statistical-models.html)

```{r,eval=F}
install.packages("neuralnet")
install.packages("clusterGeneration")
install.packages("RSNNS")
```


```{r}
library("neuralnet")
```

## [Visualizing neural networks in R – update](https://www.r-bloggers.com/visualizing-neural-networks-in-r-update/)

```{r}
library("clusterGeneration")
seed.val<-2
set.seed(seed.val)
 
num.vars<-8
num.obs<-1000
 
#input variables
cov.mat<-genPositiveDefMat(num.vars,covMethod=c("unifcorrmat"))$Sigma
rand.vars<-mvrnorm(num.obs,rep(0,num.vars),Sigma=cov.mat)
 
#output variables
parms<-runif(num.vars,-10,10)
y1<-rand.vars %*% matrix(parms) + rnorm(num.obs,sd=20)
parms2<-runif(num.vars,-10,10)
y2<-rand.vars %*% matrix(parms2) + rnorm(num.obs,sd=20)
 
#final datasets
rand.vars<-data.frame(rand.vars)
resp<-data.frame(y1,y2)
names(resp)<-c('Y1','Y2')
dat.in<-data.frame(resp,rand.vars)
```

```{r}
#nnet function from nnet package
library(nnet)
set.seed(seed.val)
mod1<-nnet(rand.vars,resp,data=dat.in,size=10,linout=T)
 
#neuralnet function from neuralnet package, notice use of only one response
library(neuralnet)
form.in<-as.formula('Y1~X1+X2+X3+X4+X5+X6+X7+X8')
set.seed(seed.val)
mod2<-neuralnet(form.in,data=dat.in,hidden=10)
 
#mlp function from RSNNS package
library(RSNNS)
set.seed(seed.val)
mod3<-mlp(rand.vars, resp, size=10,linOut=T)
```


## Resources

- Michael Nielsen - [Using neural nets to recognize handwritten digits](http://neuralnetworksanddeeplearning.com/chap1.html)