---
title: "Write a package"
author: "Jan-Philipp Kolb"
date: "21. November 2015"
output: 
  html_document: 
    keep_md: yes
---


## Writing own packages

- Hadley Wickham - [Package metadata](http://r-pkgs.had.co.nz/description.html)

- [Good R Packages](http://blog.revolutionanalytics.com/2016/05/good-r-packages.html)

- [API Packages](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html)

- [Best practices for writing an API package](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html)

- [httr quickstart guide](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html)

- [Overview - writing packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)


## Namespaces

- Karl Broman - [Writing documentation with Roxygen2 ](http://kbroman.org/pkg_primer/pages/docs.html)
- [Namespace](http://r-pkgs.had.co.nz/namespace.html)


- [nameslist - export](http://troublevn.com/41749/function-lmlist-after-installing-updating-packages-duplicate)


## Roxygen 

- [Writing documentation with roxygen2](http://kbroman.org/pkg_primer/pages/docs.html)

- [Roxygen](http://stackoverflow.com/questions/8597993/does-roxygen2-automatically-write-namespace-directives-for-imports-packages)


- Help to get the meta things right - [Roxygen 2](http://r-pkgs.had.co.nz/man.html) 


## Package Vignettes

- [Non Sweave Vignettes](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Non_002dSweave-vignettes)

- [Writing vignettes](http://kbroman.org/pkg_primer/pages/vignettes.html)

## Check routines

- [Building and testing packages](https://support.rstudio.com/hc/en-us/articles/200486508-Building-Testing-and-Distributing-Packages)

- [Package check](http://r-pkgs.had.co.nz/check.html)

- [Checking an R package ](http://kbroman.org/pkg_primer/pages/check.html)

- [Older version of R](http://stackoverflow.com/questions/1188544/getting-windows-to-start-r-in-batch-mode-using-the-start-command)

## Upload package to CRAN

- K. Broman - [Getting your R package on CRAN](http://kbroman.org/pkg_primer/pages/cran.html)

- Page to - [Submit package to CRAN](https://cran.r-project.org/submit.html)

- .tar.gz files only

## [Building and installing an R package](http://kbroman.org/pkg_primer/pages/build.html)

- If you are using windows - install [Rtools](https://cran.r-project.org/bin/windows/Rtools/)

- Open Powershell
- Go to the directory that contains your package directory.

```
R CMD build package_xy
```


- [CRAN policy](https://cran.r-project.org/submit.html)
- [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html)



## Misc

- [Naming Conventions](http://robinlovelace.net/r/2014/07/15/naming-conventions-r.html)

- [Generating .rd files](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)


- [Hidden functions in R](https://www.hsph.harvard.edu/statinformatics/soft/files/buildingrpackages.pdf)

