---
title: "Big data technologies"
author: "Jan-Philipp Kolb"
date: "20. Juli 2015"
output: ioslides_presentation
---

## R and Hadoop

- [RHadoop](https://github.com/RevolutionAnalytics/RHadoop/wiki)

```{r}
# http://rapache.net/
```

- [Step-by-Step Guide to Setting Up an R-Hadoop System](http://www.rdatamining.com/big-data/r-hadoop-setup-guide)

- [Tutorial RHadoop](http://hortonworks.com/hadoop-tutorial/using-rhadoop-to-predict-visitors-amount/)

- [R hadoop stack](http://www.r-bloggers.com/become-an-effective-data-hacker-with-the-r-hadoop-stack/)

- [Mapreduce](http://blog.revolutionanalytics.com/2011/09/mapreduce-hadoop-r.html)

## Spark

- [Running Spark on R](http://www.infoq.com/news/2014/02/sparkr-announcement)

- [Intro to SparkR](http://de.slideshare.net/KienDang5/introduction-to-sparkr)

- [Spark summit](https://www.youtube.com/watch?v=mHF3UPqLOL8)

- [Distributed computing with spark](https://www.youtube.com/watch?list=PL87GtQd0bfJzt1mZZQSj7NCRLeFdh_How&t=86&v=-TiMNoj7Rrs)

- [Starting with Spark](http://strataconf.com/big-data-conference-ca-2015/public/content/apache-spark)

## Buzz words 

- Resiliant distributed datasets (RDD)
- MapReduce


## The R-package

[Hints on the usage](http://amplab-extras.github.io/SparkR-pkg/)

```{r,eval=F}
library(devtools)
install_github("amplab-extras/SparkR-pkg", subdir="pkg")
library(SparkR)
```

