---
title: "Text Mining Twitter"
author: "Jan-Philipp Kolb"
date: "4 August 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [Getting the data](http://varianceexplained.org/r/trump-tweets/)



```{r,eval=F}
install.packages("twitteR")
install.packages("purrr")
install.packages("network")
install.packages("sna")
install.packages("qdap")
```

```{r}
lapply(c('twitteR', 'dplyr', 'ggplot2', 'lubridate', 'network', 'sna', 'qdap', 'tm'),
       library, character.only = TRUE)
```



```{r}
library(dplyr)
library(purrr)
library(twitteR)
```



```{r}
library(twitteR)
# http://thinktostart.com/twitter-authentification-with-r/
# https://apps.twitter.com/app/new
# http://iag.me/socialmedia/how-to-create-a-twitter-app-in-8-easy-steps/
# https://www.researchgate.net/post/How_do_I_extract_tweets_using_R

tweets <- userTimeline("RDataMining", n = 3200)
```

```{r}
# http://www.rdatamining.com/docs/RDataMining.pdf
```

## Links

- [Playing with Twitter data](https://www.r-bloggers.com/playing-with-twitter-data/)