---
title: "Graphical Analysis"
author: "Jan-Philipp Kolb"
date: "20 Oktober 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [Plotting Confidence Intervals](http://stackoverflow.com/questions/14069629/plotting-confidence-intervals)

```{r,eval=F}
install.packages("plotrix")
```



```{r}
# install.packages("plotrix")
library(plotrix)
set.seed(0815)
x <- 1:10
F <- runif(10,1,2) 
L <- runif(10,0,1)
U <- runif(10,2,3)

require(plotrix)
plotCI(x, F, ui=U, li=L)
```

## [Plotting Time Series](https://cran.r-project.org/web/packages/timeSeries/vignettes/timeSeriesPlot.pdf)

```{r}
# install.packages("timeSeries")
library(timeSeries)
```

```{r}
tS1 <- 100 * cumulated(LPP2005REC[, 1]) # SBI (univariate)
tS2 <- 100 * cumulated(LPP2005REC[, 1:2]) # SBI & SPI (bivariate)
tS3 <- 100 * cumulated(LPP2005REC[, 1:3]) # SBI, SPI, SWIIT (Swiss Market)
tS6 <- 100 * cumulated(LPP2005REC[, 1:6]) # Swiss and Foreign Market Indexes
5
```

```{r}
par(mfrow=c(1, 1))
plot(tS3, plot.type="s")
```


## Visualizing Categorical Data

- [Working with categorical data with R and the vcd and vcdExtra packages](https://cran.r-project.org/web/packages/vcdExtra/vignettes/vcd-tutorial.pdf)

- New Approaches in Visualization of Categorical Data: R Package extracat

## Misc 

- [Legends in Base Graphics](http://stackoverflow.com/questions/3932038/plot-a-legend-outside-of-the-plotting-area-in-base-graphics)




## Resources

- [Computing and visualizing PCA in R](https://www.r-bloggers.com/computing-and-visualizing-pca-in-r/)

- [Alternatives for boxplots](http://www.sthda.com/english/wiki/ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page-r-software-and-data-visualization)