---
title: "Data Science"
author: "Jan-Philipp Kolb"
date: "26 Juli 2016"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is data science

- [Data Science vs. Data Analytic](https://www.import.io/post/data-scientists-vs-data-analysts-why-the-distinction-matters/)

- [Data Scientist Bubble](https://blogs.oracle.com/datawarehousing/entry/why_the_data_scientist_bubble)

- [Data Science at reddit](https://www.reddit.com/r/datascience/)

- [Data science job description](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century/)

## Application of [Data science](http://www.r-bloggers.com/oreilly-data-scientist-salary-and-tools-survey-november-2014/)

- [Applications for data science](http://www.analyticsvidhya.com/blog/2015/09/applications-data-science/)

- [History of data science](http://www.forbes.com/sites/gilpress/2013/05/28/a-very-short-history-of-data-science/#42bbb11e69fd)

- [Genomics and Big Data](https://www.oreilly.com/ideas/genomics-and-the-role-of-big-data-in-personalizing-the-healthcare-experience)

## Description Data Science

- [German discussion](http://www.wiwi-treff.de/home/lounge/read.php?ukatid=14&f=28&i=279260&t=279260&collapse=1)

- [Elements of Data Science](http://image.slidesharecdn.com/bigdatachartturckzilis-120629095525-phpapp01/95/slide-1-728.jpg?cb=1340981904f)

- [How to become a data scientist (German)](http://www.focus.de/finanzen/karriere/perspektiven/arbeit-wie-werde-ich-data-scientist_id_3788707.html)

## Way to become a data scientist

- [Six steps before pursuing education data science](http://www.datascienceweekly.org/blog/26-six-steps-to-take-before-pursuing-education-to-get-a-data-science-job)

- [8 Data Skills to Get You Hired](http://blog.udacity.com/2014/11/data-science-job-skills.html)

- [Metromap Data Science](http://nirvacana.com/thoughts/wp-content/uploads/2013/07/RoadToDataScientist1.png)




## Fundamentals

- Matrices and Linear Algebra Fundamentals
- Hash Functions, Binary Tree, O(n)
- Relational Algebra, DB Basics
- Inner, Outer, Cross, Theta Join
- [CAP Theorem](https://de.wikipedia.org/wiki/CAP-Theorem)
- [Tabular Data](http://webdesign.about.com/od/tables/a/aa122605.htm)
- Data Frames and Series
- [Sharding](https://docs.mongodb.com/manual/sharding/)
-[OLAP](https://de.wikipedia.org/wiki/Online_Analytical_Processing)

- Maximum likelihood estimators
- k-nearest neighbors
- random forests
- [Ensemble methods](https://en.wikipedia.org/wiki/Ensemble_learning)

## R vs. Python for Data Science

- [KDnuggets](http://www.kdnuggets.com/2015/05/r-vs-python-data-science.html)

- [the 9 best languages for crunching data](http://www.fastcompany.com/3030716/the-9-best-languages-for-crunching-data)
