---
title: "Publishing with R and Word"
author: "Jan-Philipp Kolb"
date: "5 Dezember 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting Started

- [Happy collaboration with Rmd to docx](http://rmarkdown.rstudio.com/articles_docx.html)

- [Word Documents](http://rmarkdown.rstudio.com/word_document_format.html#style_reference)

## [ReporteRs](https://davidgohel.github.io/ReporteRs/index.html)

```{r,eval=F}
install.packages("ReporteRs")
```

- [ReporteRs](http://www.graphdoctor.com/archives/3)


## Various Topics

- [Adding the recent date to Rmarkdown document](http://stackoverflow.com/questions/23449319/yaml-current-date-in-rmarkdown)

- [Bibliographies and Citations](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

- [RStudio Formats](http://rmarkdown.rstudio.com/formats.html)

- [Creating New Formats](http://rmarkdown.rstudio.com/developer_custom_formats.html)

## Transform from LaTeX to Word

- [Converters](http://www.tug.org/utilities/texconv/textopc.html)

- [Keep TeX](http://rmarkdown.rstudio.com/pdf_document_format.html)

## Citations

[Citing R packages](http://www.carlboettiger.info/2012/03/20/citing-r-packages.html)
