---
title: "Notebooks"
author: "Jan-Philipp Kolb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    keep_md: yes
---

## Information

- [Ipython](https://ipython.org/)

- Transcript for Episode #44: [Project Jupyter and IPython](https://talkpython.fm/episodes/transcript/44/project-jupyter-and-ipython)


- [Turn a GitHub repo into a collection of interactive notebooks](http://mybinder.org/)

- [Rendering Notebooks on GitHub](http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/)
- [Presentation slides with Jupyter Notebook](http://echorand.me/presentation-slides-with-jupyter-notebook.html)

- [nbconvert](http://nbconvert.readthedocs.org/en/latest/usage.html)

- [Using both Python 2.x and Python 3.x in IPython Notebook](http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook)

## Intro Videos 

- [Intro to Ipython notebook](https://www.youtube.com/watch?v=oP9Qcjq8UVI)
- [A hands on tutorial](https://www.youtube.com/watch?v=rkx5_MRAV3A)

## Notebook with R

- [Using R with Jupyter Notebooks](http://blog.revolutionanalytics.com/2015/09/using-r-with-jupyter-notebooks.html)


[Install Rkernel](http://blog.revolutionanalytics.com/2015/09/using-r-with-jupyter-notebooks.html)

- [rmagic](https://ipython.org/ipython-doc/2/config/extensions/rmagic.html) - [rpy2](https://rpy2.bitbucket.io/)

```{python,eval=F}
python -m pip install --upgrade pip
```

- [Can't install via pip because of egg_info error](http://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error)


- [Jupyter and multiple Languages](http://carreau.github.io/posts/23-Cross-Language-Integration.html#Jupyter-and-multiple-Languages)

## R notebooks

- [Rstudio - R Notebooks](https://blog.rstudio.org/2016/10/05/r-notebooks/)

- [Rbloggers - notebook](https://www.r-bloggers.com/search/notebooks/)

## Examples

- [notebook gallery](http://nb.bianp.net/sort/views/)

- [Top 10 Ipython notebooks](http://www.kdnuggets.com/2016/04/top-10-ipython-nb-tutorials.html)

- [Echonest - we know music](http://the.echonest.com/)

- [Python from Scratch - Create a Dynamic Website](https://code.tutsplus.com/articles/python-from-scratch-create-a-dynamic-website--net-22787)

- [Snakefooding Python Code For Complexity Visualization](http://grokcode.com/864/snakefooding-python-code-for-complexity-visualization/)

- [Deploying JupyterHub for Education](https://developer.rackspace.com/blog/deploying-jupyterhub-for-education/)
- [Source & Sink](https://github.com/barbagroup/AeroPython/blob/master/lessons/01_Lesson01_sourceSink.ipynb)

- [28 Jupyter Notebook tips, tricks and shortcuts](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/)


## [Beaker Lab](https://lab.beakernotebook.com/)

- [Install on Windows](https://github.com/twosigma/beaker-notebook/wiki/Windows-build-and-run)